name: Check New Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - 'documentation/decisions/**'

env:
  PYTHON_VERSION: "3.10"

permissions:
  contents: read

concurrency: # Only run one workflow per branch at a time, and cancel any in-progress runs when a new commit is pushed
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Check if passes all requirements
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: core/esmf-aspect-meta-model-python

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          uv-version: "0.11.19"

      - name: Build esmf-aspect
        run: |
          uv sync
          uv run download-samm-release
          uv run download-samm-cli
          uv build

      - name: Run tests
        run: uv run tox -e "py${PYTHON_VERSION//./}"

      - name: Run code style checks
        run: uv run tox -e pep8
