name: Build release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true

env:
  RELEASE_VERSION: ${{ github.event.inputs.release_version }}

permissions: { }

jobs:
  check-preconditions:
    name: Check if passes all requirements
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        poetry-version: [ 1.5.0 ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python 3.10
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.10"

      - name: Run image
        uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: build esmf-aspect
        run: |
          cd core/esmf-aspect-meta-model-python
          poetry install
          poetry run download-samm-release
          poetry build

      - name: run tests
        run: |
          cd core/esmf-aspect-meta-model-python
          poetry run tox -e py310

      - name: run code style checks
        run: |
          cd core/esmf-aspect-meta-model-python
          poetry run tox -e pep8

  create_and_publish_release:
    name: Create tagged release
    needs: [ check-preconditions ]
    runs-on: ${{ matrix.os }}

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      fail-fast: false
      matrix:
        poetry-version: [ 1.5.0 ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python 3.10
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.10"

      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ matrix.poetry-version }}

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Get current version
        run: |
          cd core/esmf-aspect-meta-model-python
          version=$(poetry version -s)
          echo "current_version=${version}" >> $GITHUB_ENV

      - name: Check version incrementing
        if: ${{ !contains( env.RELEASE_VERSION, '-M' ) }}
        run: python -c "assert '${RELEASE_VERSION}' > '${current_version}'"
        shell: sh

      - name: Check version format
        if: ${{ !contains( env.RELEASE_VERSION, '-M' ) }}
        run: |
          if [[ ${RELEASE_VERSION} =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo release version is valid
          else
            echo release version ${RELEASE_VERSION} is invalid
            exit 1
          fi

      - name: Set versions
        continue-on-error: true
        run: |
          release_branch_name=${RELEASE_VERSION%.*}.x
          echo "release_branch_name=$release_branch_name" >> $GITHUB_ENV

      - name: Prepare release branch
        continue-on-error: true
        run: |
          git fetch
          git checkout -b "${release_branch_name}"
          git push --set-upstream origin "${release_branch_name}"

      - name: Checkout release branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.release_branch_name }}
          persist-credentials: false

      - name: Set antora version
        run: yq eval -i '.version = "${RELEASE_VERSION}"' documentation/python-sdk-guide/antora.yml

      - name: Set esmf-aspect project version
        id: ESMF_version
        run: |
          cd core/esmf-aspect-meta-model-python
          poetry version "${RELEASE_VERSION}"
          echo "EsmfVersion=${RELEASE_VERSION}" >> $GITHUB_ENV
          echo "EsmfVersion=${RELEASE_VERSION}" >> $GITHUB_OUTPUT

      - name: Push changes to the release branch
        run: |
          git pull
          git add documentation/python-sdk-guide/antora.yml
          git add core/esmf-aspect-meta-model-python/pyproject.toml
          git commit -m "Release version ${EsmfVersion}."
          git push

      - name: Create tag
        run: |
          tag_version=v${RELEASE_VERSION}
          git tag $tag_version
          git push origin $tag_version

      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@b78a3354a01f4a1affb484b9264b506a815c46b1 # v1.10.3
        with:
          token: ${{ github.token }}
          tag: v${{ env.RELEASE_VERSION }}
          includeInvalidCommits: true

      - name: Create and tag GitHub release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          body: ${{ steps.changelog.outputs.changes }}
          name: "Release version ${{ env.RELEASE_VERSION }}"
          tag_name: v${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish esmf-aspect-model-loader project
        run: |
          git checkout "${release_branch_name}"
          git status
          cd core/esmf-aspect-meta-model-python
          poetry install
          poetry run download-samm-release
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
